feat/item 途中経過
CreativeAI2024/CreativeAI2024 pull request #28
Opened 2024-07-11 11:16 UTC by uwatcha

現状のコードをかなたに評価してもらうためのプルリク

2024-10-05 02:32 UTC, kanata0510 commented
Itemを合成する錬金釜のようなクラスを作成して、そのなかでレシピを持っていて、それを使って合成したアイテムを返す設計にしてほしい

2024-10-14 15:00 UTC, kanata0510 reviewed
あと4倍くらい直すとこありそうなので、頑張ろう

2024-10-14 15:09 UTC, kanata0510 commented
全体的に無駄の多いコードが多かった。
あと、やりたいことをルール違反して実装している箇所が多かった。
同じ動作でもルール違反してスクリプトを書いているとバグを埋め込みやすくなったり、変更がしづらくなってしまうので後で確認しよう。
あと、名前が分かりづらいせいでクラスの設計が見えてこないので設計を確認しよう。
今のところ井田君の頭の中ではコードは完結しているかもしれないけど、僕が理解できていないので、チームの開発では他人に意図が分かりやすいコードになるようにもっと修正していこう。

2024-10-15 12:42 UTC, uwatcha commented on Assets/Scripts/ItemObjects/ItemList.cs
> +    }
修正済み

2024-10-15 12:43 UTC, uwatcha commented on Assets/Scripts/Item/CombineRecipe/CombineRecipeDatabase.cs
> +    }
この関数は自分のカバンの中を探して、引数Itemが見つからなかったらnullを返して見つからなかったことを伝えている。
try-catchを使うとエラーが起きた時の処理に見えるので、if文を使う方法に切り替えた。

2024-10-15 12:43 UTC, uwatcha commented on Assets/Scripts/Item/CombineRecipe/CombineRecipeDatabase.cs
> +    }
この関数は自分のカバンの中を探して、引数Itemが見つからなかったらnullを返して見つからなかったことを伝えている。
try-catchを使うとエラーが起きた時の処理に見えるので、if文を使う方法に切り替えた。

2024-10-15 12:47 UTC, uwatcha commented on Assets/Scripts/Item/ItemInventory.cs
> +    private HashSet<BaseItem> itemSet;
通常はItemをIsContains()に渡してItemInventory内を検索するが、アイテムのボタンオブジェクトに表示してあるアイテム名で検索しなければならない場合は、dictionaryを用いたGetItem()で検索している。
GetItem()を廃止する場合は、アイテムのボタンにそのボタンに対応するItemを保持するためだけのスクリプトを作成し、保持したそのItemをIsContains()に渡して検索する方法があるが、非効率なのでやめた。

2024-10-15 12:49 UTC, uwatcha commented on Assets/Scripts/UI/button/itemButton/SetVariabes.cs
廃止した。

2024-10-15 12:56 UTC, uwatcha commented on Assets/Scripts/UI/button/itemButton/SetVariablesImageShowCombineMaterial.cs
> +  new void Start()
修正した。

2024-10-15 12:56 UTC, uwatcha commented on Assets/Scripts/UI/compositionMaterials/CSetCombine.cs
現在は無い。

2024-10-15 13:23 UTC, uwatcha commented on Assets/Scripts/UI/button/itemButton/SetVariabes.cs
> +    thisItem = itemInventory.GetItem(transform.GetChild(0).GetComponent<TextMeshProUGUI>().text); //押したボタンのテキストからアイテムを取得 かなた質問：ボタンオブジェクトにアイテムボタンを保管するスクリプト作った方がいい？
SetVariablesを継承した複数のSetVariables~~~で、全てBaseItemへの参照が必要なので、親クラスであらかじめ参照しておいた。
(現在はこのスクリプトは使っていないが、ActionButtonというabstractクラスのthisItemも同じ意図で記述している。)

2024-10-15 13:31 UTC, uwatcha commented on Assets/Scripts/UI/button/CombineItems.cs
> +        }
「このコードがCombine()まで通らない確率が高い」ということは理解したが、「どれか一つは通るので、他のクラスでやったほうがよさそう」という文を理解できていない。どのような形での修正を意図しているか、詳しく教えていただきたい。

2024-10-15 13:33 UTC, uwatcha commented
レビューと並行してメニューUIの仕様変更をしていた影響で、使わなくなったスクリプト、新しく作成したスクリプトがあるので、１度目のレビューを受けて修正した部分も含めて再度レビューをお願いしたいです。

2024-10-15 14:35 UTC, uwatcha commented
仕様変更は完了していないので、まだバグ等も残っています。

2024-10-15 15:24 UTC, kanata0510 reviewed
いろいろ直そう

2024-10-15 15:24 UTC, kanata0510 commented on Assets/Scripts/Item/ItemInventory.cs
> +    private HashSet<Item> itemSet;
```suggestion
```
dictionaryあるからいらない

2024-10-15 15:24 UTC, kanata0510 commented on Assets/Scripts/Item/ItemInventory.cs
> +    private Dictionary<string, Item> itemDict;
```suggestion
    private Dictionary<string, int> itemDict;
```
せっかくアイテムリストがあるならindexでいいんじゃない？

2024-10-15 15:24 UTC, kanata0510 commented on Assets/Scripts/UI/button/CombineItems.cs
> +        Debug.Log("Combine() called");
DebugLogger.Log()使ってね

2024-10-15 15:24 UTC, kanata0510 commented on Assets/Scripts/UI/button/OpenWindow.cs
> +                }
もっと良くかけそう

2024-10-15 15:24 UTC, kanata0510 commented on Assets/Scripts/UI/buttons/CombineMaterialButtons.cs
> +            if (!itemInventory.GetItem(itemButton.GetChild(0).GetComponent<TextMeshProUGUI>().text)) //アイテム一覧のボタンにあってアイテムリストにないボタンを確かめる
ここでGetComponent禁止

2024-10-28 14:35 UTC, kanata0510 requested changes
バグ修正してね

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/FollowFocusedButton.cs
> +        if (previousGameObject != currentSelectedGameObject)
currentSelectedGameObjectのnullチェックはさんだほうが良さそう

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            GameObject currentSelected = EventSystem.current.currentSelectedGameObject;
currentSelectedのnullチェックはさんだほうが良さそう

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            if (_inputSetting.GetForwardKeyDown() || _inputSetting.GetBackKeyDown() || _inputSetting.GetLeftKeyDown() || _inputSetting.GetRightKeyDown() || _inputSetting.GetDecideKeyDown() || _inputS
_inputSetting.GetDecideKeyDown()は下のelse ifでも使われているので少し条件を見直した方が良さそう

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            else if (_inputSetting.GetDecideKeyDown())
本当に他の動作と同時に起こることが無いか考えたほうが良さそう

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            else if (_inputSetting.GetCancelKeyDown())
本当に他の動作と同時に起こることが無いか考えたほうが良さそう

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/button/ItemButton.cs
> +    }
```suggestion
    public int Index => transform.GetSiblingIndex();
```

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/SwitchWindow.cs
> +    private bool _isWindowActive;
```suggestion
```
キャッシュする必要がない

2024-10-28 14:35 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/SwitchWindow.cs
> +        else if (_inputSetting.GetCancelKeyDown() && _isWindowActive && menuUI.activeSelf)
activeInHierarchyを使うのか、activeSelfを使うのか、それぞれの性質の違いを理解して統一したほうが良さそう

2024-10-29 13:56 UTC, uwatcha commented on Assets/Scripts/Item/ItemInventory.cs
> +        }
した

2024-10-29 13:58 UTC, uwatcha commented on Assets/Scripts/Item/ItemInventory.cs
> +            itemDict.Add(addedItem.ItemName, addedItem);
全く問題ございません。

2024-10-29 13:59 UTC, uwatcha commented on Assets/Scripts/UI/button/actionButton/TextButton.cs
このファイルは削除しました。

2024-10-29 14:02 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            GameObject currentSelected = EventSystem.current.currentSelectedGameObject;
挟んだ

2024-10-29 14:13 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            else if (_inputSetting.GetDecideKeyDown())
同時押しはバグの元にもなりそうだから意図的に受け付けないほうが良いと思っている

2024-10-29 14:14 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            else if (_inputSetting.GetCancelKeyDown())
同時押しはバグの元にもなりそうだから意図的に受け付けないほうが良いと思っている

2024-10-29 14:15 UTC, uwatcha commented on Assets/Scripts/UI/button/ItemButton.cs
> +    }
了解した

2024-10-29 14:17 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/SwitchWindow.cs
> +    private bool _isWindowActive;
了解した

2024-10-29 14:19 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/SwitchWindow.cs
> +        else if (_inputSetting.GetCancelKeyDown() && _isWindowActive && menuUI.activeSelf)
理解&統一しました

2024-10-29 14:33 UTC, kanata0510 requested changes
ここ直したらPrefab確認してマージします

2024-10-29 14:33 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +                    OnFocused(currentSelected);
これいる？すでにカーソル移動でフォーカスされてそう

2024-10-29 14:33 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +                    OnFocused(currentSelected);
これいる？すでにカーソル移動でフォーカスされてそう

2024-10-29 14:33 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
>          if (menuUI.activeInHierarchy)
早期リターンでもっと良く書けそう

2024-10-29 14:33 UTC, kanata0510 commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            if (currentSelected != null)
早期リターンでもっと良く書けそう

2024-10-29 14:40 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +                    OnFocused(currentSelected);
子ウィンドウを開いたときに初めにFocusされるボタンのOnFocused()を呼びたい

2024-10-29 14:40 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +                    OnFocused(currentSelected);
親ウィンドウに戻ったときに初めにFocusされるボタンのOnFocused()を呼びたい

2024-10-29 14:46 UTC, uwatcha commented on Assets/Scripts/UI/uiManager/CheckCurrentSelected.cs
> +            if (currentSelected != null)
この直し方であっているだろうか

2024-10-29 15:03 UTC, kanata0510 approved these changes
大丈夫そうなのでマージします

2024-10-29 15:03 UTC, merged