メニューUIの仕様変更, 問題修正
CreativeAI2024/CreativeAI2024 pull request #88
Opened 2024-11-23 11:45 UTC by uwatcha

### 仕様変更点
- menuUI をシングルトンにした
- MenuUIManager.instance.~~で、itemInventoryのメソッドを使用できるようにした
  - これによって、itemInventoryのメソッドを使いたい時にこれをSerializeFieldで受け取る必要がなくなった
- menuUI Prefab内にCanvasを持つようにした。
  - 子オブジェクトだとDontDestroyにできないため
  - これによって、すでにCanvas内にmenuUIを配置しているSceneでは、menuUIをCanvasから出す必要がある。
### 問題修正点
- menuUI再起動時にスクロールが初期位置に戻らず、カーソルが画面外に行ってしまうことがある問題を修正
  - menuUI起動時には新しく作成したScrollToTop()というメソッドを呼ぶようにした

2024-11-26 12:29 UTC, kanata0510 commented
DontDestroySingletonにする方針でリファクタしていいと思う。
ただし、Pauseの使い方に注意したほうがいいのと、Mainという名前はどうかと思うので、そこは考えてほしい

2024-12-01 23:58 UTC, uwatcha commented
menuUI起動中にキャラクターの移動をPauseするために、room系のSceneに切り替わった時にGameObject.Find("Pause").GetComponent<Pause>();
を行って、各シーンのPauseを取得するようにしている。

もしFind()を使わない方針が良ければ、各シーンのPauseをアタッチしているオブジェクトに、「シーンが切り替わったらMenuUIManagerにPauseを送る」処理をするだけのScriptをアタッチする手がある？

2024-12-03 05:03 UTC, kanata0510 requested changes
修正たのむ

2024-12-03 05:03 UTC, kanata0510 commented on Assets/Scripts/MenuUI/MenuUIManager.cs
> +    private bool isMenuUIActive = false;
```suggestion
```
キャッシュするほどパフォーマンスに困ってないので、読みやすいように関数が呼ばれたらチェックするようにしてほしい

2024-12-03 05:03 UTC, kanata0510 commented on Assets/Scripts/MenuUI/MenuUIManager.cs
Pauseの使い方要検討したい

2024-12-03 12:27 UTC, uwatcha commented on Assets/Scripts/MenuUI/MenuUIManager.cs
> +    private bool isMenuUIActive = false;
そのように修正した

2024-12-03 12:27 UTC, uwatcha commented on Assets/Scripts/MenuUI/MenuUIManager.cs
> +    public bool GetIsMenuUIActive()
修正した

2024-12-03 12:27 UTC, uwatcha commented on Assets/Scripts/MenuUI/MenuUIManager.cs
どうしようか

2024-12-04 05:08 UTC, kanata0510 approved these changes
OKマージします

2024-12-04 05:08 UTC, merged