Feat/timing game
CreativeAI2024/CreativeAI2024 pull request #91
Opened 2024-11-25 15:12 UTC by 5884-u

一旦アイテム関連は抜きにしました

2024-11-27 12:34 UTC, 5884-u commented
アイテム関連を追加しました

2024-11-29 07:30 UTC, kanata0510 requested changes
修正たのむ

2024-11-29 07:30 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingGame.cs
さすがに何もかもやりすぎているので、判定に関わる処理は別のスクリプトに分けたほうがいいと思う。
このスクリプトでやるのは、入力を監視してバーが止まったときに時間とか回数を数えたり、結果を保存するくらい

2024-12-04 04:40 UTC, kanata0510 approved these changes
OKマージします

2024-12-04 04:41 UTC, merged