会話ウィンドウの新素材組み込み、会話を戻る機能の削除
CreativeAI2024/CreativeAI2024 pull request #93
Opened 2024-11-29 06:57 UTC by uwatcha

「次の行へ」という新しい操作案内の素材を、選択肢を表示している間は出さないようにする機能も実装している。（視覚班のデザインでそうなっていた。）

2024-11-29 07:10 UTC, kanata0510 requested changes
修正たのむ

2024-11-29 07:10 UTC, kanata0510 commented on Assets/Scripts/Text/Question.cs
> +        }
絶対にもっと良くなる。なんで70, -70にしたのか、100, 0, -100にしたのかを考えて、計算式にしてほしい。2のときは～、3のときは～、ではなくて、質問のデータの数に応じて配置するように

2024-11-29 07:18 UTC, uwatcha commented
git hubで見て気づいたけど、なぜかBGMSE内のmp3を削除するっていう変更が含まれているからそれも直します

2024-12-03 04:32 UTC, kanata0510 requested changes
修正たのむ

2024-12-03 04:32 UTC, kanata0510 commented on Assets/Scripts/Text/Question.cs
> +                center - interval * (i - (questionCount - 1) / 2f)
読めないので、説明変数を使って分かりやすくしてほしい

2024-12-04 05:12 UTC, kanata0510 approved these changes
OKマージします

2024-12-04 05:34 UTC, merged